### ISSUE TITLE
OC Miner

### ISSUE THREAD

**Issue by secinv** [vertcoin-project/one-click-miner-vnext#167] opened 2021-02-16 22:43 UTC

**Comment by vertiond** [comment] 2021-02-17 18:01
Could you please elaborate?

**Comment by gertjaap** [comment] 2021-02-18 06:13
This is a duplicate of #168

**Closed by gertjaap** 2021-02-18 06:13 UTC

**Comment by secinv** [comment] 2021-02-18 09:22
Thanks,

I sent a issue description to the GitHub

RGDS

 

Sent: Thursday, February 18, 2021 at 8:13 AM
