### ISSUE TITLE
Hashrate & Expected Earnings display issue

### ISSUE THREAD

**Issue by Semblio** [vertcoin-project/one-click-miner-vnext#217] opened 2021-02-26 05:02 UTC
When using multiple cards, OCM appears to be cycling through their individual hashrates & expected earnings instead of adding them together. I first noticed this no later than 1500 GMT on 25 February. Previously, the hashrates & expected earnings would be added together when displayed. 

I've seen this in rc16, rc12, and rc8. I have not tried other versions. I have tried deleting contents of appdata/roaming/vertcoin-ocm other than keyfile.hex and letting OCM rebuild it - no change. Restarting Windows has no apparent effect. Cards are known good, no device/driver problems, and as seen below in logs are getting work and hashing. 

My main rig is currently down, so I've only been able to check this this on one Windows 10 machine so far, with a GTX 1070 and an RX 470. 

![vtc_1](https://user-images.githubusercontent.com/8579751/109257122-716a8100-77c5-11eb-8789-20f34964d91e.PNG)
![vtc_2](https://user-images.githubusercontent.com/8579751/109257118-70395400-77c5-11eb-9843-9deccede433d.PNG)
![vtc_3](https://user-images.githubusercontent.com/8579751/109257121-716a8100-77c5-11eb-9aa6-d9752aad1326.PNG)
![vtc_4](https://user-images.githubusercontent.com/8579751/109257120-70d1ea80-77c5-11eb-9155-92a9e07ea19c.PNG)

At first glance that might just look like one mildly unstable card, but, no, it really is two, displayed hashrate is just alternating back and forth. 

2021/02/25 23:19:40.337426 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/02/25 23:19:40.337426 [DEBUG] [Miner windows/1]Daemon file already exists
2021/02/25 23:19:40.342412 [DEBUG] [Miner windows/1]Daemon file is available and correct
2021/02/25 23:19:40.342412 [DEBUG] [Miner windows/1]Removing unpack directory
2021/02/25 23:19:41.345062 [DEBUG] [Miner windows/1](Re)creating unpack directory
2021/02/25 23:19:45.284064 [DEBUG] Launching C:\Users\xxx\AppData\Roaming\vertcoin-ocm\miners\unpacked-9be5d3855c45af1077ee2e8bcc5cb688c55688dcfde5327e70f7554098ecd35d\VerthashMiner-0.7.0-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2021/02/25 23:19:45.561082 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Found 1 OpenCL devices.
2021/02/25 23:19:45.580079 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Found 1 CUDA devices
2021/02/25 23:19:45.581062 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Configuration file: (C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf) has been generated.
2021/02/25 23:19:45.665082 [DEBUG]Entering device block
2021/02/25 23:19:45.665082 [DEBUG]Exiting device block
2021/02/25 23:19:45.665082 [DEBUG]{0  false Ellesmere Advanced Micro Devices, Inc.}
2021/02/25 23:19:45.665082 [DEBUG]Entering device block
2021/02/25 23:19:45.665082 [DEBUG]Exiting device block
2021/02/25 23:19:45.665082 [DEBUG]{0  false GeForce GTX 1070 }
2021/02/25 23:19:45.665082 [DEBUG] AvailableGPUs called
2021/02/25 23:19:45.666062 [DEBUG] Launching C:\Users\xxx\AppData\Roaming\vertcoin-ocm\miners\unpacked-9be5d3855c45af1077ee2e8bcc5cb688c55688dcfde5327e70f7554098ecd35d\VerthashMiner-0.7.0-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/02/25 23:19:45.865146 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Found 1 OpenCL devices.
2021/02/25 23:19:45.885146 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Found 1 CUDA devices
2021/02/25 23:19:45.887152 [DEBUG] [VerthashMiner] [2021-02-25 23:19:45] INFO  Configuration file: (C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/02/25 23:19:46.264816 [INFO] Starting mining process...
2021/02/25 23:19:46.264816 [DEBUG] [Miner windows/1]Daemon file already exists
2021/02/25 23:19:46.268815 [DEBUG] [Miner windows/1]Daemon file is available and correct
2021/02/25 23:19:46.268815 [DEBUG] [Miner windows/1]Removing unpack directory
2021/02/25 23:19:46.668620 [DEBUG] Nethash: 2651989114
2021/02/25 23:19:46.689720 [INFO] Updating pending pool payout...
2021/02/25 23:19:47.271838 [DEBUG] [Miner windows/1](Re)creating unpack directory
2021/02/25 23:19:47.300816 [DEBUG] AvailableGPUs called
2021/02/25 23:19:47.301816 [DEBUG] Launching C:\Users\xxx\AppData\Roaming\vertcoin-ocm\miners\unpacked-9be5d3855c45af1077ee2e8bcc5cb688c55688dcfde5327e70f7554098ecd35d\VerthashMiner-0.7.0-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/02/25 23:19:47.525843 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Found 1 OpenCL devices.
2021/02/25 23:19:47.544834 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Found 1 CUDA devices
2021/02/25 23:19:47.546819 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Configuration file: (C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/02/25 23:19:47.621821 [DEBUG] Launching C:\Users\xxx\AppData\Roaming\vertcoin-ocm\miners\unpacked-9be5d3855c45af1077ee2e8bcc5cb688c55688dcfde5327e70f7554098ecd35d\VerthashMiner-0.7.0-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/02/25 23:19:47.819678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Found 1 OpenCL devices.
2021/02/25 23:19:47.837677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Found 1 CUDA devices
2021/02/25 23:19:47.837677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Using a configuration file (C:\Users\xxx\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/02/25 23:19:47.837677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:47] INFO  Loading verthash data file...
2021/02/25 23:19:48.344706 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Verthash data file has been loaded succesfully!
2021/02/25 23:19:48.344706 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Verthash data file verification stage is disabled!
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Using protocol: Stratum.
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/02/25 23:19:48.345678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/02/25 23:19:48.346677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/02/25 23:19:48.346677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/02/25 23:19:48.346677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/02/25 23:19:48.346677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/02/25 23:19:48.346677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/02/25 23:19:48.347677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/02/25 23:19:48.347677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/02/25 23:19:48.347677 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Configured 1(CL) and 1(CUDA) workers
2021/02/25 23:19:48.351678 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] DEBUG Found 1 NVML device
2021/02/25 23:19:48.381428 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  2 miner threads started, using Verthash algorithm.
2021/02/25 23:19:48.382427 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Starting Stratum on stratum+tcp://vtc.suprnova.cc:1776
2021/02/25 23:19:48.809426 [DEBUG] [VerthashMiner] [2021-02-25 23:19:48] INFO  Stratum difficulty set to 1
2021/02/25 23:19:53.589896 [DEBUG] [VerthashMiner] [2021-02-25 23:19:53] INFO  cu_device(0): temp:67C, power:94W, fan:44%, hashrate: 453.93 kH/s
2021/02/25 23:19:53.590901 [DEBUG] Device IDX: 0
2021/02/25 23:19:55.362234 [DEBUG] [VerthashMiner] [2021-02-25 23:19:55] INFO  cl_device(0): temp:62C, hashrate: 472.37 kH/s
2021/02/25 23:19:55.362234 [DEBUG] Device IDX: 0
2021/02/25 23:19:58.073468 [DEBUG] [VerthashMiner] [2021-02-25 23:19:58] INFO  cu_device(0): temp:67C, power:79W, fan:44%, hashrate: 457.31 kH/s
2021/02/25 23:19:58.073468 [DEBUG] Device IDX: 0
2021/02/25 23:19:59.363844 [DEBUG] [VerthashMiner] [2021-02-25 23:19:59] INFO  cl_device(0): temp:63C, hashrate: 486.34 kH/s
2021/02/25 23:19:59.363844 [DEBUG] Device IDX: 0
2021/02/25 23:20:02.144822 [DEBUG] [VerthashMiner] [2021-02-25 23:20:02] INFO  cu_device(0): temp:67C, power:78W, fan:44%, hashrate: 442.57 kH/s
2021/02/25 23:20:02.144822 [DEBUG] Device IDX: 0
2021/02/25 23:20:03.366987 [DEBUG] [VerthashMiner] [2021-02-25 23:20:03] INFO  cl_device(0): temp:64C, hashrate: 486.51 kH/s
2021/02/25 23:20:03.366987 [DEBUG] Device IDX: 0
2021/02/25 23:20:06.601470 [DEBUG] [VerthashMiner] [2021-02-25 23:20:06] INFO  cu_device(0): temp:67C, power:96W, fan:44%, hashrate: 443.98 kH/s
2021/02/25 23:20:06.602455 [DEBUG] Device IDX: 0
2021/02/25 23:20:07.369704 [DEBUG] [VerthashMiner] [2021-02-25 23:20:07] INFO  cl_device(0): temp:64C, hashrate: 486.50 kH/s
2021/02/25 23:20:07.369704 [DEBUG] Device IDX: 0
2021/02/25 23:20:10.606136 [DEBUG] [VerthashMiner] [2021-02-25 23:20:10] INFO  cu_device(0): temp:67C, power:96W, fan:44%, hashrate: 455.92 kH/s
2021/02/25 23:20:10.606136 [DEBUG] Device IDX: 0
2021/02/25 23:20:11.371657 [DEBUG] [VerthashMiner] [2021-02-25 23:20:11] INFO  cl_device(0): temp:64C, hashrate: 486.48 kH/s
2021/02/25 23:20:11.372631 [DEBUG] Device IDX: 0
2021/02/25 23:20:14.613279 [DEBUG] [VerthashMiner] [2021-02-25 23:20:14] INFO  cu_device(0): temp:67C, power:95W, fan:44%, hashrate: 454.42 kH/s
2021/02/25 23:20:14.613279 [DEBUG] Device IDX: 0
2021/02/25 23:20:15.374759 [DEBUG] [VerthashMiner] [2021-02-25 23:20:15] INFO  cl_device(0): temp:64C, hashrate: 486.49 kH/s
2021/02/25 23:20:15.374759 [DEBUG] Device IDX: 0
2021/02/25 23:20:18.622263 [DEBUG] [VerthashMiner] [2021-02-25 23:20:18] INFO  cu_device(0): temp:68C, power:95W, fan:44%, hashrate: 453.04 kH/s

**Comment by gertjaap** [comment] 2021-02-26 07:37
Thank you for reporting this. The problem is that you have a CUDA device (GTX) and an OpenCL device (RX). OCM doesn't deal properly with that - i'll fix it.

**Comment by vertiond** [comment] 2021-03-03 18:48
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/09083e4b22d3b1aca278ac43af377da17e2ea10b

**Closed by vertiond** 2021-03-03 18:48 UTC
