### ISSUE TITLE
Missing balance in OCM

### ISSUE THREAD

**Issue by j3di1234** [vertcoin-project/one-click-miner-vnext#590] opened 2023-12-28 01:01 UTC
Hi. My mining balance always show 0 in OCM but in Pool Web show confirmed balance.

This problems happened for days, i think start from around 23 dec 2023
Already restart OCM dan komp daily, and tried to change mining pool, but same result

![Missing Balance](https://github.com/vertcoin-project/one-click-miner-vnext/assets/155031728/ce21607d-7b21-4529-9c0a-a9f4ae973c64)

**Comment by KforG** [comment] 2023-12-29 16:15
Check your balance on OCM again.
A Backend server fetching balances was out of sync (the other one than in #588), this may have been the cause of your issue. The issue should be fixed now.

If it's still not showing, please look up your OCM address in a block explorer.

**Closed** 2024-02-06 20:55 UTC
