### ISSUE TITLE
verthash miner .3 keeps failing on nivida and amd graphics card...disapointed in this 3rd fix with amount of time that given

### ISSUE THREAD

**Issue by blaznluke007** [vertcoin-project/one-click-miner-vnext#102] opened 2021-01-30 17:39 UTC

**Comment by gertjaap** [comment] 2021-01-30 19:22
Sorry that my free work is disappointing to you and doesn't match your time tables. 

The problem is fixed in [RC4](https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/2.0-rc4)

**Closed by gertjaap** 2021-01-30 19:22 UTC
